---
- name: Debian | Set bitcoind_loaded_os_family
  set_fact:
    bitcoind_loaded_os_family: "{{ ansible_os_family }}"

- name: Debian | Adds bitcoind repository
  apt_repository:
    repo='ppa:bitcoin/bitcoin'
    state=present
  register: repo_added

- name: Debian | Update apt cache
  apt:
    update_cache=yes
  when: repo_added.changed

- name: Debian | Install bitcoind
  apt:
    name=bitcoind
    state=latest
  notify: Restart bitcoind
